FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY pkg/ ./pkg/
COPY services/search/ ./services/search/
WORKDIR /app/services/search
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/search ./cmd/main.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/bin/search .
EXPOSE 8015 50065
CMD ["./search"]
